### ISSUE TITLE
question: missing admin-interface for PageSiteMapProperties

### ISSUE THREAD

**Issue by funkyfuture** [nephila/djangocms-page-sitemap#10]
ciao, i set up the `djangocms-page-sitemap` as described in the README and it works, meaning there's a properly rendered `sitemap.xml`. there's also a table `djangocms_page_sitemap_pagesitemapproperties` in the database.

however i do not see an interface to alter the properties in the admin-backend, nor corresponding inline fields in an admin interface for a page.

am i missing something or can this be considered as bug?

OS: Ubuntu Trusty
Python: 3.4.3
Django: 1.8.12
Django CMS: 3.2.3
Django CMS Page Sitemap: 0.3.1

**Comment by funkyfuture** [comment]
ah, okay, i can access `admin/djangocms_page_sitemap/pagesitemapproperties/` when entered manually as url-path. but there's no field to select an existing page / `extended_object`.

**Comment by yakky** [comment]
@funkyfuture Hi, the page extensions admin is only meant to be available on the "Page" menu of the django CMS frontend toolbar. In that menu you handle the properties of the sitemap for the page you're on

**Comment by funkyfuture** [comment]
do you mean on a path like `en/admin/cms/page/27/` / `en/admin/cms/page/27/advanced-settings`? there it isn't.

**Comment by yakky** [comment]
@funkyfuture nope, you have to login in the frontend with http://www.yoursite.com/?edit, login and then access the frontend toolbar (see http://django-cms.readthedocs.io/en/latest/user/reference/page_admin.html for reference)

**Comment by yakky** [comment]
All the page extensions are meant to be available only on the frontend editor toolbar, not right from the admin like ![esempio4](https://cloud.githubusercontent.com/assets/714711/15548072/f8b93792-22a6-11e6-993e-9b0778adf851.png)
The address is something like https://www.yoursite.com/admin/djangocms_page_sitemap/pagesitemapproperties/add/?extended_object=514, but it's not meant to be used this way but o

**Comment by funkyfuture** [comment]
thanks a lot, that helped. i keep this issue open as a reminder to me to extend the docs when i have the time for it.

**Comment by yakky** [comment]
The above PR will document the inteface in the README.
Thanks for reporting this
