### ISSUE TITLE
Why is the extra robot values mandatory?

### ISSUE THREAD

**Issue by aufdenpunkt** [nephila/djangocms-page-sitemap#25]
Hi, 

at first I want to say thank you for this great extension, this is exactly what I need! 👍 

But could you explain, why the extra robot values field is mandatory?

Thanks and best,
Chris

**Comment by yakky** [comment]
@aufdenpunkt Agree, I've been overzealous about that
the linked PR will make it optional

**Comment by yakky** [comment]
@aufdenpunkt version 0.5.2 which includes this fix has been released

**Comment by aufdenpunkt** [comment]
@yakky Many thanks for the fix 👍
