### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by ianare** [nephila/djangocms-page-sitemap#27]
As far as I understand it, adding this module to my Django project makes the entire application GPL. This makes usage in a professional setting difficult.

I fully agree with the principle of avoiding lock-in and of having something based on your work being shared with the community, but it's a little excessive to force this on the entire application for what is in all honesty a relatively minor component of the stack.

I would gladly contribute to djangocms-page-sitemap if I make any changes to it... I'm a little less comfortable in sharing all my work and forcing my customers to do the same.

I would suggest changing the license to LGPLv3 which doesn't have the "viral" attribute of the GPL but still keeps all the other freedoms intact.

GPL is usually for entire applications, LGPL for libraries or modules.

Thank you.

**Comment by yakky** [comment]
@ianare next release will be relicensed under BSD

Thanks for raising this
