### ISSUE TITLE
utils.py emits warning: UserWarning: Pages no longer have a "site_id" attribute.

### ISSUE THREAD

**Issue by jeroenpeters1986** [nephila/djangocms-page-sitemap#28]
Hi, we are using your plugin and sometimes I am receiving this 'deprecatedwarning' for the utils file.

`/home/jeroenpeters1986/.virtualenvs/website/local/lib/python2.7/site-packages/djangocms_page_sitemap/utils.py:11: UserWarning: Pages no longer have a "site_id" attribute. To get the site id of any given page, call "site_id" on the page "node" object. This backwards compatible shim will be removed in version 3.6
`

Is this something you are familiair with and has an "easy" fix?

**Comment by yakky** [comment]
@jeroenpeters1986 yes, thanks for reporting
I opened #29 to fix this, though I will probably wait for a django CMS 3.6-compatible release to ship it in a proper release. It's going to happen in the next weeks anyway
