### ISSUE TITLE
'CMSToolbar' object has no attribute 'edit_mode'

### ISSUE THREAD

**Issue by marcosguedes** [nephila/djangocms-page-sitemap#30]
Hi everyone at Nephila . Thank you for this wonderful package.

It throws this error on Django CMS 3.6. You might already know what's going on. There's a similar request on other package that might help: https://github.com/divio/aldryn-newsblog/issues/522

I can make a PR later today if it helps.

Thanks!

Marcos

**Comment by marcosguedes** [comment]
Stacktrace

```
File "/home/marcos/.virtualenvs/myproject/lib/python3.6/site-packages/djangocms_page_sitemap/cms_toolbars.py" in populate
  41.             not_edit_mode = not self.toolbar.edit_mode

Exception Type: AttributeError at /
Exception Value: 'CMSToolbar' object has no attribute 'edit_mode'
```

**Comment by jeroenpeters1986** [comment]
I just created a PR for this

**Comment by marcosguedes** [comment]
Awesome! I completely forgot to look at it this weekend

**Comment by jeroenpeters1986** [comment]
> Awesome! I completely forgot to look at it this weekend

Not a problem, I just encountered this when I wanted to update my own installation to Django 3.6

**Comment by marcosguedes** [comment]
@jeroenpeters1986 You might also find interest in creating a PR for this issue as well https://github.com/nephila/djangocms-page-meta/issues/99

If not, I'll set a reminder to update it with your fix (and leave credits)

**Comment by jeroenpeters1986** [comment]
> @jeroenpeters1986 You might also find interest in creating a PR for this issue as well [nephila/djangocms-page-meta#99](https://github.com/nephila/djangocms-page-meta/issues/99)
> 
> If not, I'll set a reminder to update it with your fix (and leave credits)

Will do :-)
