### ISSUE TITLE
_get_cache_key moved in djangocms 3.1

### ISSUE THREAD

**Issue by panosmm** [nephila/djangocms-page-sitemap#4]
the get_cache_key function in utils includes:

    from cms.templatetags.cms_tags import _get_cache_key

In django cms 3.1

    _get_cache_key 

has been moved to

    cms.cache.__init__

**Comment by yakky** [comment]
@panosmm thanks for reporting this, fixed in develop (c826f0f8929fd7d6250cba4bcf719d6f5c257319)
