### ISSUE TITLE
Serialization issue during addon upload

### ISSUE THREAD

**Issue by kinkerl** [nephila/djangocms-page-sitemap#73]
## Description

The addon can not be uploaded to Divio Cloud because of an serialization issue.

## Steps to reproduce

Try to upload the addon to Divio cloud

## Expected behaviour

The upload should work.

## Actual behaviour

Receive a serialization issue

## Additional information

Issue was already discussed. This is the request ticket for the PR.

**Comment by yakky** [comment]
Fixed by #72 

Thanks @kinkerl for reporting the issue and fixing it
